version: "3"

services:
    frontend:
        build: .
        container_name: "react-app"
        restart: always
        ports:
          - "3000:3000"
        volumes:
          - "./src:/usr/react-app"